---
title: "New Haven GSI Stewardship"
author: "Clare Auld-Brokish (with Dexter Locke)"
date: "`r format(Sys.time())`"
output: html_document
editor_options: 
  chunk_output_type: console
---


# 0 set up
```{r}

# Load libraries 
packs <-c('tidyverse'   # cuz
          , 'tidylog'   # prints out what was done in dplyr and tidyr; VERBOSE
          # , 'tidygeocoder' # geocode addressses
          , 'tidycensus'   # access Census data
          , 'sf'           # for spatial data support
          , 'mapview'      # web maps for zooming and panning around
          , 'janitor'   # helps clean things pipe-friendly cross-tabulations
          , 'leafsync'  # linked maps
          )

if (length(setdiff(packs, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packs, rownames(installed.packages())))
}

# load the packages all at once
vapply(packs, library, character.only = TRUE, logical(1),
       logical.return = TRUE, quietly = TRUE)


```


# 1 read in data
## A Neighborhoods
```{r}

(neighs <- 
   st_read('input_data/New_Haven_Neighborhoods/Neighborhood.shp', as_tibble = TRUE) |> 
   select(Neighborhood = Neighbor_1) |> 
   st_transform(3857)
 )


neighs |> mapview()
```

## B watersheds and zonning
```{r}

sheds <- 
  st_read('../GSI STEWARDSHIP Project_data_too_big/12 digit Hydrologic Unit.geojson') |> 
  st_transform(st_crs(neighs))

mapview(neighs, alpha.regions = 0, lwd = 2) + mapview(sheds, zcol = 'Name') 

# st_layers('../GSI STEWARDSHIP Project_data_too_big/_ags_data0AA96A07DF994B819C3A75306E2DD073.gdb')

zoning <- 
  st_read('../GSI STEWARDSHIP Project_data_too_big/_ags_data0AA96A07DF994B819C3A75306E2DD073.gdb') |> 
  st_transform(st_crs(neighs))

zoning |> glimpse()
zoning |> mapview(zcol = 
                    # 'zone_code'
                    'districts'
                    # 'district_category'
                  )


```



## C GSI: City of New Haven
```{r}

list.files('../GSI STEWARDSHIP Project_data_too_big')

#stlayers is like list.files but for .gdb files
st_layers('../GSI STEWARDSHIP Project_data_too_big/50961b03-cb0b-49b9-a656-77d71bc30bbd.gdb')

inlet <- 
  st_read(  '../GSI STEWARDSHIP Project_data_too_big/50961b03-cb0b-49b9-a656-77d71bc30bbd.gdb'
          , 'inlet'
          , as_tibble = TRUE) |> 
  st_intersection(neighs) |> # adds neighborhood name
  st_intersection(sheds |> 
                    select(watershed = Name, HUC12)
                    ) |> 
  st_intersection(zoning |> 
                    select(zone_code, districts, district_category)
                  )

# did those joins work?


mapviewOptions(
    legend.pos = 'bottomleft'
  , layers.control.pos = 'topright'
  )

m_neigh <- inlet |> mapview(zcol = 'Neighborhood') # TK
m_water <- inlet |> mapview(zcol = 'watershed')
m_zone  <- inlet |> mapview(zcol = 'districts')

leafsync::sync(m_neigh, m_water, m_zone)

inspection <- 
  st_read(  '../GSI STEWARDSHIP Project_data_too_big/50961b03-cb0b-49b9-a656-77d71bc30bbd.gdb'
          , 'GI_Inspection'
          , as_tibble = TRUE) |> 
mutate(Condition=factor(CONDITION,
    levels=c("Unknown", NA, "Very Poor", "Poor", "Fair", "Good", "Very Good", "Excellent"))
  , islegit=ifelse(Condition=="Unknown" | is.na(Condition)
                   , "notlegit"
                   , "legit"))

# parcels <- 
#   st_read('/Users/dlocke/URI_data/Connecticut_Parcels.gdb', 'deepgis_DEEP_PARCEL') |> 
#   filter(TOWN == 'New Haven')
# 
# parcels |> filter(TOWN == 'New Haven') |> mapview::mapview()

# parcels <- 
#   st_read('../GSI STEWARDSHIP PROJECT/GSI STEWARDSHIP Project_data_too_big/New Haven Parcels Management.geojson') |> 
#   select(parcel_id, )
  
# Double-checks classifications
inspection |> tabyl(Condition,islegit)

# This counts "missing-ness"
inspection |> map(~sum(is.na(.))) |> bind_rows() |> t()
# CONDITION DEBRIS VEGETATION OIL   FRAME     NOTES

# Look at all the variables and glimpse data
inspection |> glimpse()

# mostly pictures
# inspection_records <- 
#   st_read(  '../GSI STEWARDSHIP Project_data_too_big/50961b03-cb0b-49b9-a656-77d71bc30bbd.gdb'
#           , 'GI_Inspection__ATTACH'
#           , as_tibble = TRUE)


# take a look
inlet |> glimpse() # transpose
inlet |> mapview(zcol = 'Install_Year')

inspection |> glimpse()

# is the unique ID really unique? 
all.equal(
  inspection |> distinct(GlobalID) |> nrow()
, inspection |> nrow()
)

# # short table to long table. 1:M
# inlet |> 
#   left_join(inspection_records, by = c('GlobalID' = 'GLOBALID'))

# # long table to short table
# inspection |> 
#   left_join(inlet, by = 'GlobalID')
# 
# 
# inlet # GlobalID
# inspection # ASSETGUID and GlobalID

# THIS WORKS
# FACILITYID is what to use?
inlet |> 
  left_join(inspection, by = c('GlobalID' = 'GlobalID')) # or ASSETGUID

# USE THIS
inlet |> # missing records are a known error
  left_join(inspection, by = 'FACILITYID') # better but missing. Patch with global

# missing records are a known error
inlet |> 
  anti_join(inspection, by = 'FACILITYID')


inlet |> 
  anti_join(inspection, by = c('GlobalID' = 'GlobalID'))


inspection_long <- 
  inspection |> 
  left_join(
    inlet |> select(-c(CreationDate, EditDate, Creator, Editor))
              , by = c('FACILITYID' = 'FACILITYID')) |> 
  select(GlobalID.x, GlobalID.y, everything()) 

inspection_long |>
  ggplot(aes(EditDate, Condition, group = ASSETGUID)) +
  geom_line(alpha = .2) +
  facet_wrap(~islegit, scales = 'free') +
  # facet_wrap(~Planting_Plan, scales = 'free') +
  NULL

inspection_long |>
  filter(islegit == 'legit') |> 
  ggplot(aes(EditDate, Condition, group = ASSETGUID)) +
  geom_line(alpha = .2) +
  theme_bw(16) +
  NULL

```

# 2 Exploratory Data Analyses
```{r}

# Tabulate frequency of the asset_GLOBALID A
(inspection_freq <- 
  inspection |> 
  tabyl(ASSETGUID) |> 
  as_tibble() |> 
  arrange(desc(n)))

# Tabulate the frequency of 

# how often have these been inspected?
inspection_freq |> summary() # roughly 4x

# what's the distribution of frequencies?
(inspection_freq_freq <- 
  inspection_freq |> 
  tabyl(n) |> 
  as_tibble())

# Base R plotting tool
inspection_freq_freq |> plot()

# pre-summarized: geom_col
inspection_freq_freq |> 
  ggplot(aes(n,n_n)) + #in the aesthetic: map the data visually
  geom_col() +
  theme_bw(16) +
  NULL #NULL shuts down the function above

inspection_freq_freq |> 
  ggplot(aes(n_n,n)) + #in the aesthetic: map the data visually
  geom_col() +
  theme_bw(16) +
  NULL

# not yet summarized: geom_bar
inspection_freq |> 
  ggplot(aes(n)) +
  # geom_bar() +
  geom_histogram() +
  # geom_density() +
  theme_bw(16) +
  NULL


inspection |> map(~sum(is.na(.))) |> bind_rows() |> t()

# FIXME Clare

## Recent Inspections
recent_inspections <- 
  inspection |> 
  group_by(ASSETGUID) |> 
  arrange(EditDate) |> 
  slice(1) |> # slice_max, slice_min instead of arrange |> slice 
  ungroup()
  
recent_inspections |> 
  tabyl(Condition) |> 
  ggplot(aes(Condition, n)) +
  geom_col()

recent_inspections |> 
  tabyl(CONDITION)

recent_inspections |> 
  tabyl(CONDITION) |> 
  as_tibble()

# try help(factor) to learn more about setting the levels of a factor
# to make them appear in order (we do NOT need an ordered factor)
recent_inspections |> 
  tabyl(Condition, islegit) |> 
  as_tibble() |> 
  pivot_longer(-Condition, names_to = "islegit") |> 
  ggplot(aes(value, Condition)) +
  geom_col() + 
  facet_wrap(~islegit, scales="free") + 
  NULL

# Repeat above code using debris, vegetation, and oil variables 
# repeat the lines above, but use DEBRIS, VEGTATION, OIL, and/or FRAME columns

# Debris Tibble
recent_inspections |> 
  group_by(DEBRIS, Condition) |> 
  count() |> 
  ggplot(aes(n, Condition)) +
  geom_col() + 
  facet_wrap(~DEBRIS, scales="free") + 
  NULL

# (recent_inspections <- # Is there a difference between inspections and recent_inspections?
  recent_inspections |> 
    tabyl(DEBRIS) |> 
  as_tibble() |> 
  arrange(desc(n))
  # )
  
# The only bioswales without debris in them were assessed in a "poor", "very poor", and "NA" condition  
recent_inspections |> 
  group_by(DEBRIS, Condition) |> 
  count() |> 
  ggplot(aes(n, Condition, fill = DEBRIS)) +
  geom_col() +
  theme_bw(16) +
  theme(legend.position = "bottom") +
  # theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5)) +
  facet_wrap(~DEBRIS) +
  # coord_flip() + 
  NULL

# # Saving charts as .png files in "figures" folder 
# ggsave( filename = paste0('figures/Debris_Condition_', Sys.Date(), '.png'))

# Vegetation Tibble 
recent_inspections |> 
  group_by(VEGETATION, Condition) |> 
  count() |> 
  ggplot(aes(n, Condition)) +
  geom_col() + 
  facet_wrap(~VEGETATION, scales="free") + 
  NULL

# Oil Tibble 
recent_inspections |> 
  group_by(OIL, Condition) |> 
  count() |> 
  ggplot(aes(n, Condition)) +
  geom_col() + 
  facet_wrap(~OIL, scales="free") + 
  NULL


gsi_per_neigh <- 
  inlet |> 
  st_drop_geometry() |> 
  group_by(Neighborhood) |> 
  count()

# Frame Tibble? I can't remember what this refers to 
recent_inspections |> 
  group_by(FRAME, Condition) |> 
  count() |> 
  ggplot(aes(n, Condition)) +
  geom_col() + 
  facet_wrap(~FRAME, scales="free") + 
  NULL


neighs |> 
  left_join(gsi_per_neigh, by = "Neighborhood") %>%
  mutate(  n = ifelse(is.na(n), 0, n)
         , area_m2 = st_area(.)
         , gsi_per_area = n / area_m2
         ) |> 
  mapview(zcol = 'gsi_per_area', layer.name = 'GSI counts /<br>neigh area')


neighs |> mapview()



```



## B Parks
```{r}

(parks <- st_read('input_data/NewHavenParksLayers_08032021/NewHavenParks.shp'))

parks |> mapview()

# parks |> mapview() + 
mapview(parks) +
  mapview(neighs, zcol = "Neighborho", layer.name = "neighborhood") +
  mapview(inlet)

```



# parcels
```{r}

parcels <- st_read('../GSI STEWARDSHIP Project_data_too_big/New Haven Parcels Management.geojson')

```


# OLD BELOW
## C GSI: URI - already folded into city data: NO NEED TO USE
```{r eval=FALSE, include=FALSE}

# Downtown only from the siting process
# ATTATCH was pictures and other field-based data

# what's in the geodatabase?
st_layers('input_data/URI_Bioswale.gdb/')

(gsi_1 <- st_read('input_data/URI_Bioswale.gdb/' # path
                  , 'Bioswales_1' # data
                  , as_tibble = TRUE) |> 
    mutate(file = 'Bioswales_1')
  )


(gsi_2 <- st_read('input_data/URI_Bioswale.gdb/' # path
                  , 'Bioswales_DT_N' # data
                  , as_tibble = TRUE) |> 
    mutate(file = 'Bioswales_DT_N')
  )

(gsi_3 <- st_read('input_data/URI_Bioswale.gdb/' # path
                  , 'Bioswales_DT_S' # data
                  , as_tibble = TRUE) |> 
    mutate(file = 'Bioswales_DT_S')
  )

# Which columns are in common?
compare_df_cols(gsi_1, gsi_2, gsi_3)


# gsi_1 |> mapview()
# gsi_2 |> mapview()
# gsi_3 |> mapview()

# mapview(gsi_1) + mapview(gsi_2) + mapview(gsi_3) 

# att_tbl <- st_read('input_data/URI_Bioswale.gdb' # path
#                    , 'Bioswales_DT_S__ATTACH' # data
#                    , as_tibble = TRUE) 

gsi <- 
  bind_rows(gsi_1, gsi_2, gsi_3)

mapview(gsi, zcol = 'file')

```






# exploratory
```{r}
gsi |> glimpse()

gsi |> select(GI_Type)

gsi |> 
  st_drop_geometry() |> #removes sticky geometries
  tabyl(file)

gsi |> 
  st_drop_geometry() |> #removes sticky geometries
  tabyl(curb_type, file)

gsi |> 
  st_drop_geometry() |> 
  tabyl(file, Install_Year,Fencing) |> 
  bind_rows(.id = "file") #counts number of GSI that meets the following conditions

gsi |> 
  st_drop_geometry() |> 
  group_by(file, Install_Year, Fencing) |> 
  summarize(n=n()) |> 
  ungroup() #makes as many variables as you want 

gsi |> 
  st_drop_geometry() |> 
  tabyl(Barrier, file)

gsi |> 
  st_drop_geometry() |> 
  tabyl(sidewalk_w, file)


```



```{r}


st_layers('../GSI STEWARDSHIP Project_data_too_big/City_layers.gdb')

thing <- st_read(
  '../GSI STEWARDSHIP Project_data_too_big/City_layers.gdb', 'NH_Publishing_SDE_DBO_NH_2016_Paved_Unpaved_Surfaces_Poly')

thing2 <- st_read(
  '../GSI STEWARDSHIP Project_data_too_big/City_layers.gdb', 'NH_Publishing_SDE_DBO_NH_2016_Structures_Poly')

mapview(thing2)
```






